name: django-test-db

services:
  postgres:
    image: postgres:17.5-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_db
    ports:
      - "25432:5432"
    volumes:
      - ./test_dev/pgsql:/var/lib/postgresql/data

  redis:
    image: redis:8.0.1-alpine
    ports:
      - "26379:6379"
    volumes:
      - ./test_dev/redis_data:/data
