name: '{{ cookiecutter.project_dir }}'

configs:
  redis_conf:
    content: |
      requirepass !!!SET DEV REDIS PASSWORD!!!

services:
  postgres:
    image: postgres:17.5-alpine3.21
    init: true
    user: '${D_UID:-1000}:${D_GID:-1000}'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=!!!SET DEV POSTGRES PASSWORD!!!
      - POSTGRES_DB=django_db
    ports:
      - '25432:5432'
    volumes:
      - ./test_dev/pgsql:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s

  redis:
    image: redis:8.2.3-alpine3.22
    init: true
    user: '${D_UID:-1000}:${D_GID:-1000}'
    ports:
      - '26379:6379'
    volumes:
      - ./test_dev/redis:/data
    configs:
      - source: redis_conf
        target: /etc/redis/redis.conf
    entrypoint:
      - redis-server
      - /etc/redis/redis.conf
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
